@startuml
'https://plantuml.com/class-diagram

start
: "/" ;
: mapping parameter : @CurrentUser Account account;
: index.html;
if (account == null) then (yes)
  :"/sign-up";
  :accountService.processNewAccount(signUpForm);
  :accountService.login(loginAccount)
else (no)
  :"/check-email";
endif
:Page.onRender();
: click sign-up button ;
: GetMapping "/sign-up" ;
: User send sign-up form data ;
end

/'

interface CurrentUser
class MainController
class AccountController
class AccountService
'/


@enduml